version: '2'
services:
  web:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/config:/ql/config
      - ./data/log:/ql/log
      - ./data/db:/ql/db
      - ./data/scripts:/ql/scripts
      - ./data/repo:/ql/repo
      - ./data/ninja:/ql/ninja
    ports:
      - "0.0.0.0:5700:5700"
      - "0.0.0.0:5701:5701"
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true

