# 5700: 青龙
# 5701: ninja
# 5702: go-cqhttp http server
# 5703: quickchart
# 5704: nvjdc
version: '2'
services:
  web:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/config:/ql/config
      - ./data/log:/ql/log
      - ./data/db:/ql/db
      - ./data/jbot:/ql/jbot
      - ./data/scripts:/ql/scripts
      - ./data/repo:/ql/repo
      - ./data/ninja:/ql/ninja
    ports:
      - "0.0.0.0:5700:5700"
      - "0.0.0.0:5701:5701"
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true

  quickchart:
    image: ianw/quickchart:latest
    container_name: quickchart
    restart: unless-stopped
    tty: true
    ports:
      - "0.0.0.0:5703:3400"

## 暂时不需要这个，有ninja够了，自己去网页里取cookie也不算太麻烦
#  nvjdc:
#    image: nolanhzy/nvjdc:latest
#    container_name: nvjdc
#    restart: unless-stopped
#    tty: true
#    privileged: true
#    ports:
#      - "0.0.0.0:5704:80"
#    volumes:
#      - ./data/nvjdc/Config.json:/app/Config/Config.json:ro
#      - ./data/nvjdc/.local-chromium:/app/.local-chromium
